Add validation flow

diff --git a/.github/workflows/start.yml b/.github/workflows/start.yml
--- a/.github/workflows/start.yml
+++ b/.github/workflows/start.yml
@@ -11,8 +11,22 @@ jobs:
         steps:
           - name: Run Local Action
             run: echo "Run Local Action"
+    
+    validation_app:
+      runs-on: ubuntu-latest
+      env:
+        APP_ID: ${{ secrets.APP_ID }}
+
+      steps:
+        - if: ${{ env.APP_ID == '' }}
+          run: |
+            echo "The app id not found"
+            exit 1
+        - if: ${{ env.APP_ID != '' }}
+          run: echo "App Valid"
 
     call_for_shared_action:
+        needs: [validation_app]
         uses: eduaranaya94/actions_base/.github/workflows/PrintMsg.yml@master
         with:
           msg: Action invoked from a remote action
